### PR TITLE
README: fix indentation levels in lists

### PR DESCRIPTION
**Pull request by mk-fg**
Will make github display it much nicer with tiered lists.

### CODE REVIEW

**Comment by mk-fg** [comment]
Having looked at the values, README seem to be outdated in the repo anyway, and disagrees with both changelog and values in Steam mod version.

**Review by HankMcKneeShank — APPROVED** [review]
Yea that looks nice

##Request approved

**Comment by mk-fg** [comment]
I think "approve" button on gh is a way to +1 PR for multiple maintainers, while you can use "Merge" to actually merge changes into repository branch.
(you probably know this already, but thought to mention as it's the first time I see anyone use github Approve button in this context)

Cheers!

**Comment by HankMcKneeShank** [comment]
@mk-fg Right now , the 2.0.3 patch has broken a lot of shit , not with my mod in particular , so if there are any issues , just tell me. Rn im very busy since im working on a megamod for stellaris that actually gives balance to the game itself and most of its issues ,which means im working on another git with some other ppl . Thanks tho for the Correction
Cheers !

**Pull request merged**
